# Generated by Django 5.1.15 on 2026-02-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0063_performancebugtemplate_no_action_required_text"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="performancealerttesting",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="performancealert",
            name="detection_method",
            field=models.CharField(max_length=100, null="unknown"),
        ),
        migrations.AlterField(
            model_name="performancealerttesting",
            name="detection_method",
            field=models.CharField(max_length=100, null="unknown"),
        ),
        migrations.AlterField(
            model_name="performancetelemetryalert",
            name="detection_method",
            field=models.CharField(max_length=100, null="unknown"),
        ),
        migrations.AlterUniqueTogether(
            name="performancealerttesting",
            unique_together={
                ("summary", "series_signature", "detection_method"),
                ("summary", "telemetry_series_signature", "detection_method"),
            },
        ),
    ]
