# Generated by Django 5.1.15 on 2026-02-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0063_performancebugtemplate_no_action_required_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancealerttesting",
            name="replicates_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
