# Generated by Django 5.1.15 on 2026-02-12 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perf", "0064_performancealerttesting_confidences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performancealerttesting",
            name="telemetry_series_signature",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="perf.performancetelemetrysignature",
            ),
        ),
    ]
