# Generated by Django 5.1.15 on 2026-02-13 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0048_alter_failureline_action"),
        ("perf", "0066_alter_performancealertsummarytesting_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="performancealertsummarytesting",
            unique_together={("repository", "framework", "prev_push", "push")},
        ),
    ]
